/**
 * 主题
 */
export const THEME_CHANGE = 'THEME_CHANGE';
export const THEME_INIT = 'THEME_INIT';
export const SHOW_THEME_VIEW = 'SHOW_THEME_VIEW';

/**
 * popular页面下拉刷新
 */
export const POPULAR_REFRESH = 'POPULAR_REFRESH';
/**
 * popular页面上拉加载失败
 */
export const POPULAR_REFRESH_FAIL = 'POPULAR_REFRESH_FAIL';
/**
 * popular页面上拉加载成功
 */
export const POPULAR_REFRESH_SUCCESS = 'POPULAR_REFRESH_SUCCESS';

export const POPULAR_LOAD_MORE_FAIL = 'POPULAR_LOAD_MORE_FAIL';

export const POPULAR_LOAD_MORE_SUCCESS = 'POPULAR_LOAD_MORE_SUCCESS';

export const POPULAR_PUSH_FAVORITE = 'POPULAR_PUSH_FAVORITE';
/**
 * trending页面下拉刷新
 */
export const TRENDING_REFRESH = 'TRENDING_REFRESH';
/**
 * trending页面上拉加载失败
 */
export const TRENDING_REFRESH_FAIL = 'TRENDING_REFRESH_FAIL';
/**
 * trending页面上拉加载成功
 */
export const TRENDING_REFRESH_SUCCESS = 'TRENDING_REFRESH_SUCCESS';
export const TRENDING_LOAD_MORE_FAIL = 'TRENDING_LOAD_MORE_FAIL';
export const TRENDING_LOAD_MORE_SUCCESS = 'TRENDING_LOAD_MORE_SUCCESS';
export const TRENDING_PUSH_FAVORITE = 'TRENDING_PUSH_FAVORITE';

export const FAVORITE_LOAD_DATA = 'FAVORITE_LOAD_DATA';
export const FAVORITE_LOAD_SUCCESS = 'FAVORITE_LOAD_SUCCESS';
export const FAVORITE_LOAD_FAIL = 'FAVORITE_LOAD_FAIL';

export const LANGUAGE_LOAD_SUCCESS = 'LANGUAGE_LOAD_SUCCESS';

export const SEARCH_LOAD_MORE_SUCCESS = 'SEARCH_LOAD_MORE_SUCCESS';
export const SEARCH_LOAD_MORE_FAIL = 'SEARCH_LOAD_MORE_FAIL';
export const SEARCH_REFRESH = 'SEARCH_REFRESH';
export const SEARCH_CANCEL = 'SEARCH_CANCEL';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const SEARCH_REFRESH_SUCCESS = 'SEARCH_REFRESH_SUCCESS';
